### ISSUE TITLE
burstpay pool support

### ISSUE THREAD

**Issue by mrowcp** [enoy19/burst-mining-pool-bot#8]
Is it possible to add support for [burstpay pool software](https://github.com/burstpay)?

**Comment by enoy19** [comment]
Hi mrowcp, thanks for your issue. Could you please provide a link to a running instance of the burstpay pool software?

**Comment by enoy19** [comment]
Found a link: http://pool.burstpay.net/

**Comment by enoy19** [comment]
@mrowcp https://github.com/burstpay/burst-pool (http://pool.burstpay.net/) was updated a year ago and might not be on the latest burst version.
